import { test, expect } from "@playwright/test";
import { clickNavAction, skipOnboarding } from "./helpers/navHelpers";

/**
 * E2E: Search + Filter + Sort — EntireClosetView.
 *
 * Runs across all configured projects (mobile + desktop).
 * Verifies search narrows results, filter panel opens/closes correctly,
 * selecting a filter adds an active pill, removing the pill restores results,
 * and the sort control changes the display order without crashing.
 */

test.describe("Search, filter and sort", () => {
	test.beforeEach(async ({ page }) => {
		await skipOnboarding(page);
		await page.goto("/");
		await expect(page.getByTestId("clothes-card").first()).toBeVisible({ timeout: 8000 });

		// Navigate to the searchable all-items view
		await clickNavAction(page, /view all/i);
		await expect(page.getByRole("main", { name: /entire closet/i })).toBeVisible({ timeout: 5000 });
	});

	test("typing a query narrows visible cards", async ({ page }) => {
		const allCards = page.getByTestId("clothes-card");
		const totalBefore = await allCards.count();

		const searchInput = page.getByLabel("Search closet");
		await searchInput.fill("dress");
		// Allow Fuse.js debounce to settle
		await page.waitForTimeout(500);

		await expect(allCards.first()).toBeVisible();
		const totalAfter = await allCards.count();
		expect(totalAfter).toBeLessThanOrEqual(totalBefore);
	});

	test("clearing the search empties the input and keeps cards visible", async ({ page }) => {
		const searchInput = page.getByLabel("Search closet");

		// Type a query
		await searchInput.fill("dress");
		await page.waitForTimeout(400);
		await expect(page.getByTestId("clothes-card").first()).toBeVisible();

		// Clear — input value goes to "" and cards are still visible (Fuse.js returns all on empty query)
		await searchInput.fill("");
		await page.waitForTimeout(400);
		await expect(searchInput).toHaveValue("");
		await expect(page.getByTestId("clothes-card").first()).toBeVisible();
	});

	test("filter panel opens and closes", async ({ page }) => {
		const filterBtn = page.locator(".search-sort-bar__filter-btn");
		const panel = page.locator(".filter-side-panel");

		// Open — CSS class and aria-hidden reflect state
		await filterBtn.click();
		await expect(panel).toHaveClass(/filter-side-panel--open/, { timeout: 3000 });

		// Close via dedicated "Close filters" button
		await page.getByRole("button", { name: /close filters/i }).click();
		await expect(panel).not.toHaveClass(/filter-side-panel--open/, { timeout: 3000 });
	});

	test("selecting a category filter adds a pill and narrows results", async ({ page }) => {
		const filterBtn = page.locator(".search-sort-bar__filter-btn");
		const panel = page.locator(".filter-side-panel");

		await filterBtn.click();
		await expect(panel).toHaveClass(/filter-side-panel--open/, { timeout: 3000 });

		// Expand the Category accordion (it's a <button> inside the panel)
		await panel.getByRole("button", { name: /category/i }).click();

		// Wait for the Category accordion body, then click the "tops" option.
		// The input id is "filter-Category-tops" (generated by FilterAccordion).
		// The panel is portaled to document.body, so scope to page not panel.
		const categoryGroup = page.locator('[role="group"][aria-label="Category"]');
		await expect(categoryGroup).toBeVisible({ timeout: 3000 });
		await page.locator("#filter-Category-tops").click();

		// Close the panel
		await page.getByRole("button", { name: /close filters/i }).click();

		// An active-filter pill for "tops" should appear in the pills row
		const pillsRow = page.getByLabel("Active filters");
		await expect(pillsRow).toBeVisible({ timeout: 3000 });
		await expect(pillsRow.getByText(/tops/i)).toBeVisible();

		// Some cards visible (filtered to tops only)
		await expect(page.getByTestId("clothes-card").first()).toBeVisible();
	});

	test("removing a filter pill shows more results than when filtered", async ({ page }) => {
		const allCards = page.getByTestId("clothes-card");

		// Apply "tops" filter
		const filterBtn = page.locator(".search-sort-bar__filter-btn");
		const panel = page.locator(".filter-side-panel");
		await filterBtn.click();
		await expect(panel).toHaveClass(/filter-side-panel--open/, { timeout: 3000 });
		await panel.getByRole("button", { name: /category/i }).click();
		const categoryGroup = panel.getByRole("group", { name: "Category" });
		await expect(categoryGroup).toBeVisible({ timeout: 3000 });
		await categoryGroup.getByText("tops", { exact: true }).click();
		await page.getByRole("button", { name: /close filters/i }).click();

		const filteredCount = await allCards.count();

		// Remove the pill
		const removePill = page.getByLabel(/remove tops filter/i);
		await expect(removePill).toBeVisible({ timeout: 3000 });
		await removePill.click();

		// Wait for React to re-render the grid
		await page.waitForTimeout(400);

		// Pills row disappears and more items are shown
		await expect(page.getByLabel("Active filters")).toBeHidden({ timeout: 3000 });
		const restoredCount = await allCards.count();
		expect(restoredCount).toBeGreaterThan(filteredCount);
	});

	test("sort dropdown changes display order without error", async ({ page }) => {
		const sortSelect = page.getByLabel("Sort items");
		await expect(sortSelect).toBeVisible();

		// Record which option is current, pick a different one
		const options = await sortSelect.locator("option").allTextContents();
		const currentValue = await sortSelect.inputValue();
		const alternateLabel = options.find((o) => o !== currentValue) ?? options[1];
		await sortSelect.selectOption({ label: alternateLabel });

		// Cards still render (sort doesn't break the view)
		await expect(page.getByTestId("clothes-card").first()).toBeVisible();
	});
});
