import { Option } from "./types.ts";

export const formItem = {
	id: "",
	type: "",
	color: "",
	size: "",
	brand: "",
	material: "",
	occasion: "",
	age: "",
	care: "",
};

export const colorOptions = ["red", "brown", "black", "grey", "white", "floral", "blue", "gold", "green"];

export const sizeOptions = ["xs", "s", "m", "l", "0", "2", "4", "6", "8"];

export const clothesAgesOptions = ["new", "1 month", "3 months", "6 months", "1 year", "18 months", "3 years", "vintage", "unknown"];

export const brandExamples = ["aritzia", "zara", "gap", "express", "fenty", "lulu lemon"];

export const materialExamples = ["cotton", "silk", "wool", "cashmier", "polyester", "modal", "lace"];

export const occasionExamples = ["formal", "wedding", "cocktail", "going-out", "casual", "church", "picknic", "wear to work", "everyday", "vacation"];

export const careExamples = ["dry clean only", "hand wash", "cold water", "hot water", "low heat", "hang dry", "lay flat dry"];

// Categories for the carousel
export const carouselCategories = [
	{ label: "Tops", icon: "👕" },
	{ label: "Bottoms", icon: "👖" },
	{ label: "Dresses", icon: "👗" },
	{ label: "Coats", icon: "🧥" },
	{ label: "Sweaters", icon: "🧶" },
	{ label: "Active", icon: "🏋️‍♀️" },
	{ label: "Lingerie", icon: "🎀" },
	{ label: "Socks", icon: "🧦" },
	{ label: "Underwear", icon: "🩲" },
];

export const categoryOptions: Option[] = [
	{ value: "tops", label: "Tops" },
	{ value: "bottoms", label: "Bottoms" },
	{ value: "dresses", label: "Dresses" },
	{ value: "coats", label: "Coats" },
	{ value: "sweaters", label: "Sweaters" },
	{ value: "active", label: "Active" },
	{ value: "lingerie", label: "Lingerie" },
	{ value: "socks", label: "Socks" },
	{ value: "underwear", label: "Underwear" },
];

export type ClothingItem = {
	id: string | number;
	imageURL: string;
	name: string;
	category: string;
	color: string;
	size: string;
	brand: string;
	price?: string;
	material: string;
	occasion: string;
	age: string;
	care: string | string[];
	onSale?: boolean;
	notes?: string | string[];
};

const ClothingItemPossibilities = {
	id: "id number",
	imageURL: "url to image of clothing",
	name: " describe the clothing",
	category: categoryOptions,
	color: colorOptions,
	size: sizeOptions,
	brand: brandExamples,
	price: "USD",
	material: materialExamples,
	occasion: occasionExamples,
	age: clothesAgesOptions,
	care: careExamples,
	notes: "anything",
};

export const MY_CLOSET_DATA = [
	{
		id: "001",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378561/Screenshot_2025-10-13_at_11.02.15_AM_iigax2.png",
		name: "Sculpt Knit Racer Mini Dress | Bodycon Knit Pink dress",
		category: "dress",
		color: "pink",
		size: "M",
		brand: "aritzia",
		price: "$43.99",
		material: "knitt",
		occasion: "sporty",
		age: "one year",
		care: "hand wash",
		notes: "anything",
		onSale: true,
	},
	{
		id: "002",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378561/Screenshot_2025-10-13_at_11.01.47_AM_cteckm.png",
		name: "Chill Malibu Dress | Black spagettig strap",
		category: "dress",
		color: "black",
		size: "M",
		brand: "aritzia",
		price: "$19.99",
		material: "knitt",
		occasion: "everyday",
		age: "one year",
		care: "hand wash",
		notes: "anything",
		onSale: true,
	},
	{
		id: "003",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378933/Screenshot_2025-10-13_at_11.07.40_AM_ywvcnu.png",
		name: "Boyfriend Linen Shirt | White Buttonup",
		category: "top",
		color: "white",
		size: "M",
		brand: "aritzia",
		price: "$34.99",
		material: "linen",
		occasion: "wear to work",
		age: "one year",
		care: ["cold water", "hang dry"],
		notes: ["has a snag", " and a stain", "needs to be washed"],
		onSale: true,
	},
	{
		id: "004",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378564/Screenshot_2025-10-13_at_11.01.56_AM_bj8hhy.png",
		name: "Contour Squareneck Mini Dress | Bodycon soft dress",
		category: "dress",
		color: "green",
		size: "L",
		brand: "aritzia",
		price: "$38.99",
		material: "modal",
		occasion: "everyday",
		age: "one year",
		care: "hand wash",
		notes: ["fits a little big around the waste"],
		onSale: true,
	},
	{
		id: "005",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378560/Screenshot_2025-10-13_at_11.02.21_AM_wtckqg.png",
		name: "Sculpt Knit Squareneck Mini Dress | Brown midi dress",
		category: "dress",
		color: "brown",
		size: "L",
		brand: "aritzia",
		price: "$32.99",
		material: "knitt",
		occasion: "everyday",
		age: "one year",
		care: "hand wash",
		notes: ["loose everywhere"],
		onSale: true,
	},

	{
		id: "006",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378929/Screenshot_2025-10-13_at_11.07.28_AM_n555pt.png",
		name: "Contour Off-shoulder Longsleeve Dress | Black off the shoulder dress",
		category: "dress",
		color: "black",
		size: "L",
		brand: "aritzia",
		price: "$34.99",
		material: "modal",
		occasion: "going out",
		age: "one year",
		care: "hand wash",
		notes: ["lost at the dry clearns on the upper east side"],
		onSale: true,
	},
	{
		id: "007",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760425172/Screenshot_2025-10-13_at_11.59.09_PM_gb0zvn.png",
		name: "Chill Malibu Dress | Roughed Black mini dress",
		category: "dress",
		color: "black",
		size: "M",
		brand: "aritzia",
		price: "$19.99",
		material: "modal",
		occasion: "casual",
		age: "one year",
		care: "hand wash",
		notes: ["hang dry"],
		onSale: true,
	},
	{
		id: "008",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378928/Screenshot_2025-10-13_at_11.08.13_AM_auiyu5.png",
		name: "Pleated Pant | High waisted wide leg grey trousers",
		category: "bottom",
		color: "grey",
		size: "4",
		brand: "aritzia",
		price: "$148",
		material: "61% recycled polyester",
		occasion: "work",
		age: "two year",
		care: "machine wash cold",
		notes: [
			"Majo loves these",
			"long, must wear with heels",
			" These are high-waisted, relaxed-fit pants with a pleated front and slash hand pockets.  Expertly tailored in (Re)ssential — softly structured stretch fabric that holds its form while you move easy. ",
		],
		onSale: false,
	},

	{
		id: "009",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760467752/Screenshot_2025-10-14_at_11.48.56_AM_fxlwhs.png",
		name: "High-rise A-line mini skirt | black skirt",
		category: "bottom",
		color: "black",
		size: "M",
		brand: "aritzia",
		price: "$14.99",
		material: "65% LENZING™ ECOVERO™ Viscose, 30% nylon, 5% elastane",
		occasion: "going out",
		age: "two years",
		care: "machine wash",
		notes: [
			"wear with tights",
			"This is a high-rise bodycon mini skirt with an elastic waist. It's knit with stretchy double-knit ponte made from LENZING™ ECOVERO™ Viscose",
		],
		onSale: true,
	},
	{
		id: "010",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378930/Screenshot_2025-10-13_at_11.07.46_AM_izbebo.png",
		name: "Destiny Blazer | Double-breasted blazer with shoulder pads",
		category: "coat",
		color: "Heather Turner Taupe Grey",
		size: "6",
		brand: "aritzia",
		price: "$166",
		material: "Content: 61% recycled polyester, 26% LENZING™ ECOVERO™ Viscose, 7% cotton, 6% elastane; Lining: 100% cupro",
		occasion: "work",
		age: "two years",
		care: "dry clean",
		notes: [
			"loose fitting",
			" This is a classic double-breasted blazer with a peaked lapel, welt pockets and shoulder pads. It's made with (Re)ssential — softly structured stretch fabric that holds its form while you move easy. ",
		],
		onSale: false,
	},
	{
		id: "011",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760468900/Screenshot_2025-10-14_at_12.03.34_PM_id3je6.png",
		name: "Sherpa Car Coat | Double-breasted blazer with shoulder pads",
		category: "coat",
		color: "brown",
		size: "M",
		brand: "Banana Republic",
		price: "$128.54",
		// was 400
		material: "Shell: 100% polyester; Lining: 100% cupro rayon",
		occasion: "winter",
		age: "two years",
		care: "machine wash",
		notes: [
			"loose fitting",
			"Take a trip of unexpected luxury with this sumptuously soft sherpa coat with meticulous diamond quilted lining to keep you cozy on every adventure. Oversized. Notch collar. Button closure. On-seam pockets. Two interior pockets. WARMER: Lightly lined with quilted lining so you can layer it through the seasons ",
			"Below-knee length",
		],
		onSale: true,
	},
	{
		id: "012",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378933/Screenshot_2025-10-13_at_11.07.52_AM_o4sbhu.png",
		name: "Deniro Vest | Softly structured button-up suit vest",
		category: "top",
		color: "heather dark grey",
		size: "4",
		brand: "Aritzia",
		price: "$118",
		// was 400
		material: "Content: 61% polyester, 26% viscose, 7% cotton, 6% elastane; Lining: 100% cupro",
		occasion: "wear to work",
		age: "two years",
		care: "dry clean",
		notes: [
			"tight across boobs fitting",
			"This is a button-up vest with a classic fit and princess seams for shaping. ",
			"Fit: Classic — Follows your contours with a little room",
		],
		onSale: false,
	},
	{
		id: "013",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760469087/Screenshot_2025-10-14_at_12.11.15_PM_tindak.png",
		name: "Black Knit Oversized Sweater ",
		category: "sweater",
		color: "black",
		size: "S",
		brand: "Lulus",
		price: "$35",
		// was 44
		material: "95% Cotton, 5% Spandex",
		occasion: "casual",
		age: "4 years",
		care: "hand wash cold",
		notes: ["we fight about this", "fits perfect"],
		onSale: true,
	},
];

export const CLOSET_DATA = [
	{
		id: 100,
		imageURL: "https://static.zara.net/assets/public/8e51/b145/80904ae19a15/6e521e09414a/09314210822-a2/09314210822-a2.jpg?ts=1760022031725&amp;w=336",
		name: "black halter short dress",
		category: "dress",
		color: "red",
		size: "M",
		brand: "Zara",
		material: "cotton",
		occasion: "casual",
		age: 18,
		care: "wash like colors",
	},
];

export const CHAT_CLOSET_DATA: ClothingItem[] = [
	// --- Tops (≥10) ---
	{
		id: 1,
		imageURL: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
		name: "classic white tee",
		category: "tops",
		color: "white",
		size: "m",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 2,
		imageURL: "https://images.pexels.com/photos/1002645/pexels-photo-1002645.jpeg",
		name: "black tank top",
		category: "tops",
		color: "black",
		size: "s",
		brand: "gap",
		material: "modal",
		occasion: "casual",
		age: "3 months",
		care: "wash like colors",
	},
	{
		id: 3,
		imageURL: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
		name: "floral crop top",
		category: "tops",
		color: "floral",
		size: "xs",
		brand: "express",
		material: "silk",
		occasion: "going-out",
		age: "1 month",
		care: "hand wash",
	},
	{
		id: 4,
		imageURL: "https://images.pexels.com/photos/2983465/pexels-photo-2983465.jpeg",
		name: "blue button-down shirt",
		category: "tops",
		color: "blue",
		size: "l",
		brand: "aritzia",
		material: "cotton",
		occasion: "formal",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 5,
		imageURL: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
		name: "green blouse",
		category: "tops",
		color: "green",
		size: "m",
		brand: "fenty",
		material: "lace",
		occasion: "casual",
		age: "new",
		care: "hand wash",
	},
	{
		id: 6,
		imageURL: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
		name: "grey long sleeve tee",
		category: "tops",
		color: "grey",
		size: "m",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "1 year",
		care: "cold water",
	},
	{
		id: 7,
		imageURL: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
		name: "red off shoulder top",
		category: "tops",
		color: "red",
		size: "s",
		brand: "express",
		material: "polyester",
		occasion: "going-out",
		age: "3 months",
		care: "wash like colors",
	},
	{
		id: 8,
		imageURL: "https://images.pexels.com/photos/2983465/pexels-photo-2983465.jpeg",
		name: "black halter neck",
		category: "tops",
		color: "black",
		size: "m",
		brand: "zara",
		material: "silk",
		occasion: "cocktail",
		age: "new",
		care: "dry clean only",
	},
	{
		id: 9,
		imageURL: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
		name: "white sleeveless blouse",
		category: "tops",
		color: "white",
		size: "l",
		brand: "aritzia",
		material: "cotton",
		occasion: "formal",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 10,
		imageURL: "https://images.pexels.com/photos/2983465/pexels-photo-2983465.jpeg",
		name: "floral camisole",
		category: "tops",
		color: "floral",
		size: "m",
		brand: "fenty",
		material: "lace",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},

	// --- Bottoms (≥10) ---
	{
		id: 11,
		imageURL: "https://images.pexels.com/photos/853151/pexels-photo-853151.jpeg",
		name: "blue jeans",
		category: "bottoms",
		color: "blue",
		size: "4",
		brand: "gap",
		material: "cotton",
		occasion: "casual",
		age: "1 year",
		care: "cold water",
	},
	{
		id: 12,
		imageURL: "https://images.pexels.com/photos/39811/pexels-photo-39811.jpeg",
		name: "black trousers",
		category: "bottoms",
		color: "black",
		size: "6",
		brand: "zara",
		material: "polyester",
		occasion: "formal",
		age: "6 months",
		care: "dry clean only",
	},
	{
		id: 13,
		imageURL: "https://images.pexels.com/photos/2983465/pexels-photo-2983465.jpeg",
		name: "green cargo pants",
		category: "bottoms",
		color: "green",
		size: "8",
		brand: "express",
		material: "cotton",
		occasion: "casual",
		age: "3 months",
		care: "cold water",
	},
	{
		id: 14,
		imageURL: "https://images.pexels.com/photos/853151/pexels-photo-853151.jpeg",
		name: "white shorts",
		category: "bottoms",
		color: "white",
		size: "2",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 15,
		imageURL: "https://images.pexels.com/photos/39811/pexels-photo-39811.jpeg",
		name: "grey joggers",
		category: "bottoms",
		color: "grey",
		size: "m",
		brand: "lulu lemon",
		material: "modal",
		occasion: "casual",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 16,
		imageURL: "https://images.pexels.com/photos/853151/pexels-photo-853151.jpeg",
		name: "brown corduroy pants",
		category: "bottoms",
		color: "brown",
		size: "l",
		brand: "aritzia",
		material: "cotton",
		occasion: "casual",
		age: "3 months",
		care: "wash like colors",
	},
	{
		id: 17,
		imageURL: "https://images.pexels.com/photos/39811/pexels-photo-39811.jpeg",
		name: "gold satin skirt",
		category: "bottoms",
		color: "gold",
		size: "s",
		brand: "express",
		material: "silk",
		occasion: "cocktail",
		age: "new",
		care: "hand wash",
	},
	{
		id: 18,
		imageURL: "https://images.pexels.com/photos/853151/pexels-photo-853151.jpeg",
		name: "floral midi skirt",
		category: "bottoms",
		color: "floral",
		size: "m",
		brand: "zara",
		material: "lace",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},
	{
		id: 19,
		imageURL: "https://images.pexels.com/photos/39811/pexels-photo-39811.jpeg",
		name: "black pencil skirt",
		category: "bottoms",
		color: "black",
		size: "4",
		brand: "gap",
		material: "polyester",
		occasion: "formal",
		age: "6 months",
		care: "dry clean only",
	},
	{
		id: 20,
		imageURL: "https://images.pexels.com/photos/853151/pexels-photo-853151.jpeg",
		name: "blue denim shorts",
		category: "bottoms",
		color: "blue",
		size: "6",
		brand: "aritzia",
		material: "cotton",
		occasion: "casual",
		age: "1 month",
		care: "cold water",
	},

	// --- Dresses (≥10) ---
	{
		id: 21,
		imageURL: "https://images.pexels.com/photos/461428/pexels-photo-461428.jpeg",
		name: "red midi dress",
		category: "dresses",
		color: "red",
		size: "m",
		brand: "express",
		material: "silk",
		occasion: "cocktail",
		age: "new",
		care: "dry clean only",
	},
	{
		id: 22,
		imageURL: "https://images.pexels.com/photos/793618/pexels-photo-793618.jpeg",
		name: "black wrap dress",
		category: "dresses",
		color: "black",
		size: "s",
		brand: "zara",
		material: "cotton",
		occasion: "formal",
		age: "3 months",
		care: "hand wash",
	},
	{
		id: 23,
		imageURL: "https://images.pexels.com/photos/995676/pexels-photo-995676.jpeg",
		name: "white slip dress",
		category: "dresses",
		color: "white",
		size: "xs",
		brand: "aritzia",
		material: "silk",
		occasion: "wedding",
		age: "new",
		care: "dry clean only",
	},
	{
		id: 24,
		imageURL: "https://images.pexels.com/photos/420778/pexels-photo-420778.jpeg",
		name: "green sundress",
		category: "dresses",
		color: "green",
		size: "l",
		brand: "fenty",
		material: "cotton",
		occasion: "casual",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 25,
		imageURL: "https://images.pexels.com/photos/2559941/pexels-photo-2559941.jpeg",
		name: "blue shift dress",
		category: "dresses",
		color: "blue",
		size: "m",
		brand: "express",
		material: "polyester",
		occasion: "going-out",
		age: "1 year",
		care: "wash like colors",
	},
	{
		id: 26,
		imageURL: "https://images.pexels.com/photos/2725020/pexels-photo-2725020.jpeg",
		name: "floral maxi dress",
		category: "dresses",
		color: "floral",
		size: "m",
		brand: "zara",
		material: "lace",
		occasion: "wedding",
		age: "new",
		care: "hand wash",
	},
	{
		id: 27,
		imageURL: "https://images.pexels.com/photos/4602431/pexels-photo-4602431.jpeg",
		name: "grey sweater dress",
		category: "dresses",
		color: "grey",
		size: "s",
		brand: "aritzia",
		material: "wool",
		occasion: "casual",
		age: "3 months",
		care: "lay flat dry",
	},
	{
		id: 28,
		imageURL: "https://images.pexels.com/photos/4548702/pexels-photo-4548702.jpeg",
		name: "brown shift dress",
		category: "dresses",
		color: "brown",
		size: "l",
		brand: "express",
		material: "cotton",
		occasion: "work",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 29,
		imageURL: "https://images.pexels.com/photos/3719631/pexels-photo-3719631.jpeg",
		name: "gold evening gown",
		category: "dresses",
		color: "gold",
		size: "m",
		brand: "fenty",
		material: "silk",
		occasion: "formal",
		age: "new",
		care: "dry clean only",
	},
	{
		id: 30,
		imageURL: "https://images.pexels.com/photos/461428/pexels-photo-461428.jpeg",
		name: "black slip dress",
		category: "dresses",
		color: "black",
		size: "s",
		brand: "zara",
		material: "silk",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},

	// --- Coats (≥10) ---
	{
		id: 31,
		imageURL: "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg",
		name: "black trench coat",
		category: "coats",
		color: "black",
		size: "l",
		brand: "zara",
		material: "cotton",
		occasion: "formal",
		age: "1 year",
		care: "dry clean only",
	},
	{
		id: 32,
		imageURL: "https://images.pexels.com/photos/373965/pexels-photo-373965.jpeg",
		name: "brown leather jacket",
		category: "coats",
		color: "brown",
		size: "m",
		brand: "aritzia",
		material: "leather",
		occasion: "casual",
		age: "3 years",
		care: "dry clean only",
	},
	{
		id: 33,
		imageURL: "https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg",
		name: "grey wool overcoat",
		category: "coats",
		color: "grey",
		size: "l",
		brand: "zara",
		material: "wool",
		occasion: "formal",
		age: "1 year",
		care: "dry clean only",
	},
	{
		id: 34,
		imageURL: "https://images.pexels.com/photos/428341/pexels-photo-428341.jpeg",
		name: "white faux fur coat",
		category: "coats",
		color: "white",
		size: "m",
		brand: "fenty",
		material: "polyester",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},
	{
		id: 35,
		imageURL: "https://images.pexels.com/photos/373965/pexels-photo-373965.jpeg",
		name: "blue rain jacket",
		category: "coats",
		color: "blue",
		size: "l",
		brand: "express",
		material: "polyester",
		occasion: "casual",
		age: "6 months",
		care: "hang dry",
	},
	{
		id: 36,
		imageURL: "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg",
		name: "green parka",
		category: "coats",
		color: "green",
		size: "m",
		brand: "zara",
		material: "polyester",
		occasion: "casual",
		age: "1 year",
		care: "hang dry",
	},
	{
		id: 37,
		imageURL: "https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg",
		name: "floral trench coat",
		category: "coats",
		color: "floral",
		size: "s",
		brand: "express",
		material: "cotton",
		occasion: "going-out",
		age: "new",
		care: "cold water",
	},
	{
		id: 38,
		imageURL: "https://images.pexels.com/photos/428341/pexels-photo-428341.jpeg",
		name: "gold bomber jacket",
		category: "coats",
		color: "gold",
		size: "m",
		brand: "aritzia",
		material: "polyester",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},
	{
		id: 39,
		imageURL: "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg",
		name: "black leather coat",
		category: "coats",
		color: "black",
		size: "l",
		brand: "gap",
		material: "leather",
		occasion: "formal",
		age: "3 years",
		care: "dry clean only",
	},
	{
		id: 40,
		imageURL: "https://images.pexels.com/photos/373965/pexels-photo-373965.jpeg",
		name: "white trench coat",
		category: "coats",
		color: "white",
		size: "m",
		brand: "zara",
		material: "cotton",
		occasion: "formal",
		age: "6 months",
		care: "cold water",
	},

	// --- Sweaters (≥10) ---
	{
		id: 41,
		imageURL: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
		name: "grey crewneck sweater",
		category: "sweaters",
		color: "grey",
		size: "s",
		brand: "aritzia",
		material: "cashmier",
		occasion: "casual",
		age: "1 year",
		care: "lay flat dry",
	},
	{
		id: 42,
		imageURL: "https://images.pexels.com/photos/2983465/pexels-photo-2983465.jpeg",
		name: "white cable knit sweater",
		category: "sweaters",
		color: "white",
		size: "m",
		brand: "zara",
		material: "wool",
		occasion: "casual",
		age: "6 months",
		care: "hand wash",
	},
	{
		id: 43,
		imageURL: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
		name: "black turtleneck",
		category: "sweaters",
		color: "black",
		size: "l",
		brand: "gap",
		material: "cotton",
		occasion: "formal",
		age: "new",
		care: "cold water",
	},
	{
		id: 44,
		imageURL: "https://images.pexels.com/photos/461428/pexels-photo-461428.jpeg",
		name: "green v-neck sweater",
		category: "sweaters",
		color: "green",
		size: "m",
		brand: "fenty",
		material: "modal",
		occasion: "casual",
		age: "3 months",
		care: "lay flat dry",
	},
	{
		id: 45,
		imageURL: "https://images.pexels.com/photos/793618/pexels-photo-793618.jpeg",
		name: "red wool pullover",
		category: "sweaters",
		color: "red",
		size: "s",
		brand: "express",
		material: "wool",
		occasion: "casual",
		age: "new",
		care: "hand wash",
	},
	{
		id: 46,
		imageURL: "https://images.pexels.com/photos/420778/pexels-photo-420778.jpeg",
		name: "floral cardigan",
		category: "sweaters",
		color: "floral",
		size: "m",
		brand: "zara",
		material: "lace",
		occasion: "going-out",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 47,
		imageURL: "https://images.pexels.com/photos/995676/pexels-photo-995676.jpeg",
		name: "gold knit sweater",
		category: "sweaters",
		color: "gold",
		size: "l",
		brand: "gap",
		material: "polyester",
		occasion: "cocktail",
		age: "new",
		care: "hand wash",
	},
	{
		id: 48,
		imageURL: "https://images.pexels.com/photos/2725020/pexels-photo-2725020.jpeg",
		name: "grey crew knit",
		category: "sweaters",
		color: "grey",
		size: "m",
		brand: "aritzia",
		material: "modal",
		occasion: "casual",
		age: "1 year",
		care: "lay flat dry",
	},
	{
		id: 49,
		imageURL: "https://images.pexels.com/photos/2983465/pexels-photo-2983465.jpeg",
		name: "black zip sweater",
		category: "sweaters",
		color: "black",
		size: "s",
		brand: "fenty",
		material: "cotton",
		occasion: "casual",
		age: "3 months",
		care: "cold water",
	},
	{
		id: 50,
		imageURL: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
		name: "white cropped sweater",
		category: "sweaters",
		color: "white",
		size: "m",
		brand: "zara",
		material: "wool",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},

	// --- Lingerie (≥10) ---
	{
		id: 51,
		imageURL: "https://images.pexels.com/photos/3748221/pexels-photo-3748221.jpeg",
		name: "black lace bralette",
		category: "lingerie",
		color: "black",
		size: "s",
		brand: "fenty",
		material: "lace",
		occasion: "casual",
		age: "new",
		care: "hand wash",
	},
	{
		id: 52,
		imageURL: "https://images.pexels.com/photos/3748222/pexels-photo-3748222.jpeg",
		name: "white satin slip",
		category: "lingerie",
		color: "white",
		size: "m",
		brand: "zara",
		material: "silk",
		occasion: "wedding",
		age: "new",
		care: "dry clean only",
	},
	{
		id: 53,
		imageURL: "https://images.pexels.com/photos/3748223/pexels-photo-3748223.jpeg",
		name: "red lace bodysuit",
		category: "lingerie",
		color: "red",
		size: "s",
		brand: "express",
		material: "lace",
		occasion: "going-out",
		age: "3 months",
		care: "hand wash",
	},
	{
		id: 54,
		imageURL: "https://images.pexels.com/photos/3748224/pexels-photo-3748224.jpeg",
		name: "floral bralette",
		category: "lingerie",
		color: "floral",
		size: "xs",
		brand: "aritzia",
		material: "lace",
		occasion: "casual",
		age: "1 month",
		care: "hand wash",
	},
	{
		id: 55,
		imageURL: "https://images.pexels.com/photos/3748225/pexels-photo-3748225.jpeg",
		name: "black silk chemise",
		category: "lingerie",
		color: "black",
		size: "m",
		brand: "gap",
		material: "silk",
		occasion: "formal",
		age: "6 months",
		care: "hand wash",
	},
	{
		id: 56,
		imageURL: "https://images.pexels.com/photos/3748226/pexels-photo-3748226.jpeg",
		name: "green lace bra",
		category: "lingerie",
		color: "green",
		size: "s",
		brand: "fenty",
		material: "lace",
		occasion: "casual",
		age: "new",
		care: "hand wash",
	},
	{
		id: 57,
		imageURL: "https://images.pexels.com/photos/3748227/pexels-photo-3748227.jpeg",
		name: "white bralette",
		category: "lingerie",
		color: "white",
		size: "l",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 58,
		imageURL: "https://images.pexels.com/photos/3748228/pexels-photo-3748228.jpeg",
		name: "grey lace thong",
		category: "lingerie",
		color: "grey",
		size: "s",
		brand: "express",
		material: "lace",
		occasion: "casual",
		age: "3 months",
		care: "hand wash",
	},
	{
		id: 59,
		imageURL: "https://images.pexels.com/photos/3748229/pexels-photo-3748229.jpeg",
		name: "gold silk slip",
		category: "lingerie",
		color: "gold",
		size: "m",
		brand: "fenty",
		material: "silk",
		occasion: "formal",
		age: "new",
		care: "dry clean only",
	},
	{
		id: 60,
		imageURL: "https://images.pexels.com/photos/3748230/pexels-photo-3748230.jpeg",
		name: "floral sleep set",
		category: "lingerie",
		color: "floral",
		size: "m",
		brand: "aritzia",
		material: "modal",
		occasion: "casual",
		age: "6 months",
		care: "cold water",
	},

	// --- Socks (≥10) ---
	{
		id: 61,
		imageURL: "https://images.pexels.com/photos/19090/pexels-photo.jpg",
		name: "black crew socks",
		category: "socks",
		color: "black",
		size: "s",
		brand: "gap",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 62,
		imageURL: "https://images.pexels.com/photos/19091/pexels-photo.jpg",
		name: "white ankle socks",
		category: "socks",
		color: "white",
		size: "m",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 63,
		imageURL: "https://images.pexels.com/photos/19092/pexels-photo.jpg",
		name: "grey athletic socks",
		category: "socks",
		color: "grey",
		size: "l",
		brand: "aritzia",
		material: "polyester",
		occasion: "casual",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 64,
		imageURL: "https://images.pexels.com/photos/19093/pexels-photo.jpg",
		name: "black dress socks",
		category: "socks",
		color: "black",
		size: "m",
		brand: "express",
		material: "cotton",
		occasion: "formal",
		age: "1 year",
		care: "cold water",
	},
	{
		id: 65,
		imageURL: "https://images.pexels.com/photos/19094/pexels-photo.jpg",
		name: "blue stripe socks",
		category: "socks",
		color: "blue",
		size: "s",
		brand: "gap",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 66,
		imageURL: "https://images.pexels.com/photos/19095/pexels-photo.jpg",
		name: "floral crew socks",
		category: "socks",
		color: "floral",
		size: "m",
		brand: "zara",
		material: "modal",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 67,
		imageURL: "https://images.pexels.com/photos/19096/pexels-photo.jpg",
		name: "brown wool socks",
		category: "socks",
		color: "brown",
		size: "l",
		brand: "aritzia",
		material: "wool",
		occasion: "casual",
		age: "3 months",
		care: "lay flat dry",
	},
	{
		id: 68,
		imageURL: "https://images.pexels.com/photos/19097/pexels-photo.jpg",
		name: "red ankle socks",
		category: "socks",
		color: "red",
		size: "m",
		brand: "express",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 69,
		imageURL: "https://images.pexels.com/photos/19098/pexels-photo.jpg",
		name: "green stripe socks",
		category: "socks",
		color: "green",
		size: "s",
		brand: "fenty",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 70,
		imageURL: "https://images.pexels.com/photos/19099/pexels-photo.jpg",
		name: "gold shimmer socks",
		category: "socks",
		color: "gold",
		size: "s",
		brand: "zara",
		material: "polyester",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},

	// --- Underwear (≥10) ---
	{
		id: 71,
		imageURL: "https://images.pexels.com/photos/3748231/pexels-photo-3748231.jpeg",
		name: "black boxer briefs",
		category: "underwear",
		color: "black",
		size: "m",
		brand: "gap",
		material: "cotton",
		occasion: "casual",
		age: "1 year",
		care: "cold water",
	},
	{
		id: 72,
		imageURL: "https://images.pexels.com/photos/3748232/pexels-photo-3748232.jpeg",
		name: "white briefs",
		category: "underwear",
		color: "white",
		size: "l",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "new",
		care: "cold water",
	},
	{
		id: 73,
		imageURL: "https://images.pexels.com/photos/3748233/pexels-photo-3748233.jpeg",
		name: "grey boxer briefs",
		category: "underwear",
		color: "grey",
		size: "s",
		brand: "aritzia",
		material: "modal",
		occasion: "casual",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 74,
		imageURL: "https://images.pexels.com/photos/3748234/pexels-photo-3748234.jpeg",
		name: "blue bikini brief",
		category: "underwear",
		color: "blue",
		size: "m",
		brand: "express",
		material: "polyester",
		occasion: "casual",
		age: "new",
		care: "hand wash",
	},
	{
		id: 75,
		imageURL: "https://images.pexels.com/photos/3748235/pexels-photo-3748235.jpeg",
		name: "floral boxer briefs",
		category: "underwear",
		color: "floral",
		size: "m",
		brand: "zara",
		material: "cotton",
		occasion: "casual",
		age: "3 months",
		care: "cold water",
	},
	{
		id: 76,
		imageURL: "https://images.pexels.com/photos/3748236/pexels-photo-3748236.jpeg",
		name: "red bikini",
		category: "underwear",
		color: "red",
		size: "s",
		brand: "fenty",
		material: "polyester",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},
	{
		id: 77,
		imageURL: "https://images.pexels.com/photos/3748237/pexels-photo-3748237.jpeg",
		name: "green briefs",
		category: "underwear",
		color: "green",
		size: "l",
		brand: "gap",
		material: "cotton",
		occasion: "casual",
		age: "6 months",
		care: "cold water",
	},
	{
		id: 78,
		imageURL: "https://images.pexels.com/photos/3748238/pexels-photo-3748238.jpeg",
		name: "gold shimmer briefs",
		category: "underwear",
		color: "gold",
		size: "m",
		brand: "zara",
		material: "polyester",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},
	{
		id: 79,
		imageURL: "https://images.pexels.com/photos/3748239/pexels-photo-3748239.jpeg",
		name: "white seamless brief",
		category: "underwear",
		color: "white",
		size: "s",
		brand: "aritzia",
		material: "modal",
		occasion: "casual",
		age: "3 months",
		care: "cold water",
	},
	{
		id: 80,
		imageURL: "https://images.pexels.com/photos/3748240/pexels-photo-3748240.jpeg",
		name: "black bikini",
		category: "underwear",
		color: "black",
		size: "m",
		brand: "express",
		material: "polyester",
		occasion: "going-out",
		age: "new",
		care: "hand wash",
	},

	// Could add more for any categories lacking count, up to 100
	// e.g. additional dresses, coats, skirts, etc.
];
