import type { ClothingItem, ItemStatus, WearState } from "./types";

const b = (material: string, percentage: number) => ({ material, percentage });

const DEMO_ITEMS: ClothingItem[] = [
	{
		id: "001",
		status: "dirty" as ItemStatus,
		locationId: "home",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378561/Screenshot_2025-10-13_at_11.02.15_AM_iigax2.png",
		name: "Sculpt Knit Racer Mini Dress | Bodycon Knit Pink dress",
		category: "dress",
		color: "pink",
		size: "M",
		brand: "aritzia",
		price: 43.99,
		purchaseDate: "2026-06-05T21:11:11.000Z",
		condition: "good" as WearState,
		material: [
			{ material: "nylon", percentage: 99 },
			{ material: "elastane", percentage: 1 },
		],
		occasion: "elevated",
		care: ["hand wash", "lay flat"],
		notes: [
			"faint oil stain",
			"This is a racerback mini dress with a crew neckline and fully fashioned construction",
			"This garment is constructed using an Ottoman stitch with close distinct ribs for a structured and textural feel. ",
			"Fit: Tight — A close fit that hugs the body",
			"Length: Mini — Intended to hit between mid thigh and low thigh",
		],
		onSale: true,
	},
	{
		id: "002",
		status: "on_loan" as ItemStatus,
		locationId: "other",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378561/Screenshot_2025-10-13_at_11.01.47_AM_cteckm.png",
		name: "Henrietta Dress | Black spaghetti strap",
		category: "dress",
		color: "black",
		size: "S",
		brand: "aritzia",
		price: 38.99,
		purchaseDate: "2023-03-07T05:59:07.000Z",
		condition: "good" as WearState,
		material: [
			{ material: "viscose", percentage: 48 },
			{ material: "polyester", percentage: 30 },
			{ material: "nylon", percentage: 19 },
			{ material: "elastane", percentage: 3 },
		],
		occasion: "casual",
		care: ["machine wash", "cold water", "lay flat"],
		notes: [
			"This is a cami mini dress with adjustable straps and fully fashioned construction",
			"Double Knit stitch for structure and a flat, dense feel",
		],
		onSale: true,
	},
	{
		id: "003",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378933/Screenshot_2025-10-13_at_11.07.40_AM_ywvcnu.png",
		name: "Boyfriend Linen Shirt | White Buttonup",
		category: "top",
		color: "white",
		size: "L",
		brand: "aritzia",
		price: 34.99,
		purchaseDate: "2026-06-05T21:11:11.000Z",
		condition: "good" as WearState,
		material: [
			{ material: "linen", percentage: 55 },
			{ material: "viscose", percentage: 45 },
		],
		occasion: "preppy",
		care: ["machine wash", "cold water", "hang dry"],
		notes: [
			"yellows easily",
			"This is a long-sleeve button-up shirt with a front patch pocket, raglan sleeves and a rounded hem",
			"relaxed fit",
		],
		onSale: true,
	},
	{
		id: "004",
		status: "traveling" as ItemStatus,
		locationId: "suitcase",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378564/Screenshot_2025-10-13_at_11.01.56_AM_bj8hhy.png",
		name: "Contour Squareneck Mini Dress | Bodycon soft dress",
		category: "dress",
		color: "green",
		size: "L",
		brand: "aritzia",
		price: 38.99,
		purchaseDate: "2026-06-05T21:11:11.000Z",
		material: [
			{ material: "nylon", percentage: 94 },
			{ material: "elastane", percentage: 6 },
		],
		occasion: "elevated",
		care: ["hand wash", "cold water", "lay flat"],
		notes: [
			"fits a little big around the waste",
			"This is a mini tank dress with a double square neckline. It's made with Babaton's signature Contour — luxe, ultra-flattering fabric coveted for its smoothing effect and second-skin feel",
		],
		onSale: true,
	},
	{
		id: "005",
		status: "at_cleaner" as ItemStatus,
		locationId: "home",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378560/Screenshot_2025-10-13_at_11.02.21_AM_wtckqg.png",
		name: "Sculpt Knit Squareneck Mini Dress | Brown midi dress",
		category: "dress",
		color: "brown",
		size: "L",
		brand: "aritzia",
		price: 32.99,
		condition: "new" as WearState,
		material: [
			{ material: "nylon", percentage: 99 },
			{ material: "elastane", percentage: 1 },
		],
		occasion: "elevated",
		purchaseDate: "2024-08-20T03:24:08.000Z",
		care: ["hand wash", "hang dry"],
		notes: [
			"loose everywhere",
			"with tags",
			"This garment is constructed using an Ottoman stitch with close distinct ribs for a structured and textural feel. ",
		],
		onSale: true,
	},

	{
		id: "006",
		status: "clean" as ItemStatus,
		locationId: "storage",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378929/Screenshot_2025-10-13_at_11.07.28_AM_n555pt.png",
		name: "Contour Off-shoulder Longsleeve Dress | Black off the shoulder dress",
		category: "dress",
		color: "black",
		size: "L",
		brand: "aritzia",
		price: 34.99,
		material: [
			{ material: "nylon", percentage: 94 },
			{ material: "elastane", percentage: 6 },
		],
		occasion: "going out",
		age: "one year",
		care: ["hand wash", "hang dry"],
		notes: ["lost at the dry clearns on the upper east side"],
		onSale: true,
	},
	{
		id: "007",
		status: "in_repair" as ItemStatus,
		locationId: "home",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760425172/Screenshot_2025-10-13_at_11.59.09_PM_gb0zvn.png",
		name: "Chill Malibu Dress | Roughed Black mini dress",
		category: "dress",
		color: "black",
		size: "M",
		brand: "aritzia",
		price: 19.99,
		material: [
			{ material: "cotton", percentage: 95 },
			{ material: "elastane", percentage: 5 },
		],
		occasion: "casual",
		purchaseDate: "2026-06-05T21:11:11.000Z",
		care: ["machine wash", "cold water"],
		notes: ["Fit: Slim — Streamlined to fit close to the body", "Length: Mini — Intended to hit between mid thigh and low thigh"],
		onSale: true,
	},
	{
		id: "008",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378928/Screenshot_2025-10-13_at_11.08.13_AM_auiyu5.png",
		name: "Babaton Pleated Pant | High waisted wide leg grey trousers",
		category: "bottom",
		color: "grey",
		size: "4",
		brand: "aritzia",
		price: 148,
		material: [
			{ material: "polyester", percentage: 61 },
			{ material: "viscose", percentage: 26 },
			{ material: "cotton", percentage: 7 },
			{ material: "elastane", percentage: 6 },
		],
		occasion: "work",
		purchaseDate: "2023-03-07T05:59:07.000Z",
		care: ["machine wash", "cold water"],
		notes: [
			"long, must wear with heels",
			" These are high-waisted, relaxed-fit pants with a pleated front and slash hand pockets.  Expertly tailored in (Re)ssential — softly structured stretch fabric that holds its form while you move easy. ",
			"Softly structured high-waisted wide-leg pleated pants",
		],
		onSale: false,
	},

	{
		id: "009",
		status: "clean" as ItemStatus,
		locationId: "suitcase",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760467752/Screenshot_2025-10-14_at_11.48.56_AM_fxlwhs.png",
		name: "High-rise A-line mini skirt | black skirt",
		category: "bottom",
		color: "black",
		size: "M",
		brand: "aritzia",
		price: 14.99,
		material: [
			{ material: "viscose", percentage: 65 },
			{ material: "nylon", percentage: 30 },
			{ material: "elastane", percentage: 5 },
		],
		condition: "good" as WearState,
		occasion: "going out",
		purchaseDate: "2023-08-17T03:24:11.000Z",
		care: ["machine wash", "lay flat"],
		notes: ["wear with tights", "This is a high-rise bodycon mini skirt with an elastic waist. It's knit with stretchy double-knit ponte"],
		onSale: true,
	},
	{
		id: "010",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378930/Screenshot_2025-10-13_at_11.07.46_AM_izbebo.png",
		name: "Destiny Blazer | Double-breasted blazer with shoulder pads",
		category: "coat",
		color: "Heather Turner Taupe Grey",
		size: "6",
		brand: "aritzia",
		price: 166,
		material: [b("recycled polyester", 61), b("viscose", 26), b("cotton", 7), b("elastane", 6)],
		occasion: "work",
		purchaseDate: "2023-08-23T01:59:09.000Z",
		condition: "good" as WearState,
		care: "dry clean",
		notes: [
			"loose fitting",
			" This is a classic double-breasted blazer with a peaked lapel, welt pockets and shoulder pads. It's made with (Re)ssential — softly structured stretch fabric that holds its form while you move easy. ",
		],
		onSale: false,
	},
	{
		id: "011",
		status: "traveling" as ItemStatus,
		locationId: "suitcase",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1781163001/l_wp_699bd186ff353a34a178dd67_es6xwd.webp",
		name: "Serres Sherpa Car Coat",
		category: "coat",
		color: "brown",
		size: "M",
		brand: "Banana Republic",
		price: 128.54,
		material: [b("polyester", 100)],
		occasion: "winter",
		condition: "good" as WearState,
		purchaseDate: "2023-01-19T21:19:18.000Z",
		care: "machine wash",
		notes: [
			"loose fitting",
			"Take a trip of unexpected luxury with this sumptuously soft sherpa coat with meticulous diamond quilted lining to keep you cozy on every adventure. Oversized. Notch collar. Button closure. On-seam pockets. Two interior pockets. WARMER: Lightly lined with quilted lining so you can layer it through the seasons ",
			"Below-knee length",
			"SHERPA: Luxuriously soft, this vegan-friendly faux fur fabric looks and feels even better than the real thing. WARMEST: Fully lined and ultra-cozy, this style is designed to keep you warm through the coldest days. Wide notch lapel, Front pockets, Center back vent, Fully lined, Semi-fitted with room through the chest, arms and waist, Long sleeves, Knee length",
			"Take a trip of unexpected luxury with this sumptuously soft sherpa coat with meticulous diamond quilted lining to keep you cozy on every adventure. Oversized, WARMER: Lightly lined with quilted lining so you can layer it through the seasons., OVERSIZED FIT: Expertly cut for a loose fit. Size down if you prefer more form-fitting., Notch collar. Button closure., On-seam pockets. Two interior pockets., Fully lined., Product #506005",
		],
		onSale: true,
	},
	{
		id: "012",
		status: "clean" as ItemStatus,
		locationId: "storage",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760378933/Screenshot_2025-10-13_at_11.07.52_AM_o4sbhu.png",
		name: "Deniro Vest | Softly structured button-up suit vest",
		category: "top",
		color: "heather dark grey",
		size: "4",
		brand: "Aritzia",
		price: 118,
		material: [b("polyester", 61), b("viscose", 26), b("cotton", 7), b("elastane", 6)],
		occasion: "wear to work",
		condition: "good" as WearState,
		purchaseDate: "2023-01-19T21:19:18.000Z",
		care: "dry clean",
		notes: [
			"tight across boobs fitting",
			"This is a button-up vest with a classic fit and princess seams for shaping. ",
			"Fit: Classic — Follows your contours with a little room",
		],
		onSale: false,
	},
	{
		id: "013",
		imageURL: "https://res.cloudinary.com/dh41vh9dx/image/upload/v1760469087/Screenshot_2025-10-14_at_12.11.15_PM_tindak.png",
		name: "Black Knit Oversized Sweater ",
		category: "sweater",
		color: "black",
		size: "S",
		brand: "Lulus",
		price: 35,
		material: [b("cotton", 95), b("spandex", 5)],
		purchaseDate: "2021-11-10T01:02:37.000Z",
		condition: "needs_repair" as WearState,
		occasion: "casual",
		care: " wash cold",
		notes: ["fits perfect", "small hole"],
		onSale: true,
	},
];

/**
 * The starter closet. Every item is tagged `isDemo: true` so it can be shown
 * locally (a new user's closet isn't empty) while being excluded from every
 * cloud write (BUG-2) and targeted by the "clear demo data" prompt. Tagging
 * here — one immutable map — guarantees no demo object can ever ship untagged.
 */
export const MY_CLOSET_DATA: ClothingItem[] = DEMO_ITEMS.map((item) => ({ ...item, isDemo: true }));
