import type { RegexMap } from "../types";

export const COLOR_MAP: RegexMap = [
  [/\bblack\b/i, "black"],
  [/\bwhite\b/i, "white"],
  [/\bnavy\b/i, "navy"],
  [/\bivory\b/i, "ivory"],
  [/\bcream\b/i, "cream"],
  [/\bburgundy\b/i, "burgundy"],
  [/\bmaroon\b/i, "maroon"],
  [/\bcharcoal\b/i, "charcoal"],
  [/\bheather[- ]?grey\b/i, "heather grey"],
  [/\bgrey\b/i, "grey"],
  [/\bgray\b/i, "gray"],
  [/\bolive\b/i, "olive"],
  [/\bkhaki\b/i, "khaki"],
  [/\btan\b/i, "tan"],
  [/\bcamel\b/i, "camel"],
  [/\bcognac\b/i, "cognac"],
  [/\bcoral\b/i, "coral"],
  [/\bblush\b/i, "blush"],
  [/\bmauve\b/i, "mauve"],
  [/\blavender\b/i, "lavender"],
  [/\bsage\b/i, "sage"],
  [/\bmint\b/i, "mint"],
  [/\bteal\b/i, "teal"],
  [/\brust\b/i, "rust"],
  [/\bmustard\b/i, "mustard"],
  [/\bred\b/i, "red"],
  [/\bblue\b/i, "blue"],
  [/\bgreen\b/i, "green"],
  [/\byellow\b/i, "yellow"],
  [/\bpink\b/i, "pink"],
  [/\bpurple\b/i, "purple"],
  [/\borange\b/i, "orange"],
  [/\bbrown\b/i, "brown"],
  [/\bgold\b/i, "gold"],
  [/\bsilver\b/i, "silver"],
];
