import type { RegexMap } from "../types";

export const MATERIAL_MAP: RegexMap = [
  [/\bcotton\b/i, "cotton"],
  [/\blinen\b/i, "linen"],
  [/\bsilk\b/i, "silk"],
  [/\bsatin\b/i, "satin"],
  [/\bchiffon\b/i, "chiffon"],
  // Smartwool (REI brand) is a merino-wool blend; treat the brand token as wool.
  [/\bsmartwool\b/i, "wool"],
  [/\bwool\b/i, "wool"],
  [/\bcashmere\b/i, "cashmere"],
  [/\bmerino\b/i, "merino wool"],
  [/\bdenim\b/i, "denim"],
  [/\bflannel\b/i, "flannel"],
  [/\bvelvet\b/i, "velvet"],
  [/\bcorduroy\b/i, "corduroy"],
  [/\bfaux[- ]?leather\b/i, "faux leather"],
  [/\bleather\b/i, "leather"],
  [/\bsuede\b/i, "suede"],
  [/\bpolyester\b/i, "polyester"],
  [/\brayon\b/i, "rayon"],
  [/\bnylon\b/i, "nylon"],
  [/\bspandex\b/i, "spandex"],
  [/\blycra\b/i, "lycra"],
  [/\bjersey\b/i, "jersey"],
  [/\bknit\b/i, "knit"],
  [/\bcrochet\b/i, "crochet"],
  [/\borganza\b/i, "organza"],
  [/\btulle\b/i, "tulle"],
  [/\blace\b/i, "lace"],
  [/\bmesh\b/i, "mesh"],
  [/\bterry\b/i, "terry"],
  [/\bfleece\b/i, "fleece"],
  [/\bscuba\b/i, "scuba"],
  [/\bcrepe\b/i, "crepe"],
  [/\btwill\b/i, "twill"],
];
