import type { RegexMap } from "../types";

export const NECKLINE_MAP: RegexMap = [
	[/\b(square[- ]?neck|squareneck)\b/i, "square neck"],
	[/\b(v[- ]?neck|vneck)\b/i, "v-neck"],
	[/\bcrew[- ]?neck\b/i, "crew neck"],
	[/\b(scoop[- ]?neck|scoopneck|scoop)\b/i, "scoop neck"],
	[/\b(boat[- ]?neck|boatneck)\b/i, "boat neck"],
	[/\b(cowl[- ]?neck|cowlneck)\b/i, "cowl neck"],
	[/\b(turtle[- ]?neck|turtleneck)\b/i, "turtleneck"],
	[/\b(mock[- ]?neck|mockneck)\b/i, "mock neck"],
	[/\bsweetheart\b/i, "sweetheart"],
	[/\bstrapless\b/i, "strapless"],
	[/\b(one[- ]?shoulder)\b/i, "one shoulder"],
	[/\b(off[- ]?(the[- ]?)?shoulder)\b/i, "off-shoulder"],
	[/\bcold[- ]?shoulder\b/i, "cold shoulder"],
	[/\bhalter\b/i, "halter"],
	[/\bplunge\b/i, "plunge"],
	[/\bkeyhole\b/i, "keyhole"],
	[/\btie[- ]?neck\b/i, "tie neck"],
	[/\bhenley\b/i, "henley"],
	[/\bjewel\b/i, "jewel"],
	[/\bportrait\b/i, "portrait"],
	[/\billusion\b/i, "illusion"],
	[/\bnotch\b/i, "notch"],
	[/\bsplit[- ]?neck\b/i, "split neck"],
	[/\bmandarin[- ]?collar\b/i, "mandarin collar"],
	[/\bcamp[- ]?collar\b/i, "camp collar"],
	[/\bjohnny[- ]?collar\b/i, "johnny collar"],
	[/\bpeter[- ]?pan[- ]?collar\b/i, "peter pan collar"],
	[/\bspread[- ]?collar\b/i, "spread collar"],
	[/\bpoint[- ]?collar\b/i, "point collar"],
	[/\bshawl[- ]?collar\b/i, "shawl collar"],
	[/\bcollared\b/i, "collared"],
	[/\blapel\b/i, "lapel"],
];
