// ---------------------------------------------------------------------------
// Zara order confirmation email (real HTML from Gmail)
// ---------------------------------------------------------------------------
export const ZARA_EMAIL_BODY = [
	'<div style="font:11px/1.231 arial,clean,sans-serif;margin:70px 25px">',
	'<div style="height:21px;padding-bottom:11px;margin-bottom:50px">',
	'<h1 style="text-align:center"><img alt="ZARA" src="http://static.zara.net/wcsstore/ZaraStorefrontAssetStore/images/logo_Zara.png"></h1>',
	"</div>",
	'<div style="padding:45px 0">',
	'<h2 style="font-size:22px;margin-bottom:50px">Thank you for your purchase</h2>',
	'<div style="padding-bottom:11px">',
	'<table cellspacing="0" cellpadding="0" style="width:100%;margin-top:20px;font-size:12px">',
	'<thead style="text-transform:uppercase;font-size:12px">',
	"<tr>",
	"<th>Description</th><th>Reference</th><th>Colour</th><th>Size</th><th>Units</th><th>Amount</th>",
	"</tr></thead>",
	"<tbody>",
	// Product 1
	'<tr style="height:32px">',
	"<td>",
	'<table><tbody><tr><td><img height="83px" src="https://static.zara.net/photos/1112051420_1_1_1.jpg" alt=""></td>',
	'<td><span style="vertical-align:middle;font-size:12px">SHORT JACQUARD JUMPSUIT</span></td></tr></tbody></table>',
	"</td>",
	"<td>0/1112/051/420/03</td>",
	"<td>Bluish</td>",
	"<td>M</td>",
	"<td>1</td>",
	"<td>29.99&nbsp;USD</td>",
	"</tr>",
	// Product 2
	'<tr style="height:32px">',
	"<td>",
	'<table><tbody><tr><td><img height="83px" src="https://static.zara.net/photos/4331014600_1_1_1.jpg" alt=""></td>',
	'<td><span style="vertical-align:middle;font-size:12px">KNOTTED TOP</span></td></tr></tbody></table>',
	"</td>",
	"<td>0/4331/014/600/04</td>",
	"<td>Red</td>",
	"<td>L</td>",
	"<td>1</td>",
	"<td>19.99&nbsp;USD</td>",
	"</tr>",
	// Product 3
	'<tr style="height:32px">',
	"<td>",
	'<table><tbody><tr><td><img height="83px" src="https://static.zara.net/photos/7684230800_1_1_1.jpg" alt=""></td>',
	'<td><span style="vertical-align:middle;font-size:12px">LACE LAPEL JUMPSUIT</span></td></tr></tbody></table>',
	"</td>",
	"<td>0/7684/230/800/03</td>",
	"<td>Black</td>",
	"<td>M</td>",
	"<td>1</td>",
	"<td>69.90&nbsp;USD</td>",
	"</tr>",
	// Product 4
	'<tr style="height:32px">',
	"<td>",
	'<table><tbody><tr><td><img height="83px" src="https://static.zara.net/photos/8004023401_1_1_1.jpg" alt=""></td>',
	'<td><span style="vertical-align:middle;font-size:12px">WIDE-LEG PANTS WITH CONTRASTING TOPSTITCHING</span></td></tr></tbody></table>',
	"</td>",
	"<td>0/8004/023/401/03</td>",
	"<td>Navy blue</td>",
	"<td>M</td>",
	"<td>1</td>",
	"<td>29.99&nbsp;USD</td>",
	"</tr>",
	// Product 5
	'<tr style="height:32px">',
	"<td>",
	'<table><tbody><tr><td><img height="83px" src="https://static.zara.net/photos/3200301040_1_1_1.jpg" alt=""></td>',
	'<td><span style="vertical-align:middle;font-size:12px">PLATFORM SLINGBACK SHOES</span></td></tr></tbody></table>',
	"</td>",
	"<td>1/3200/301/040/39</td>",
	"<td>Black</td>",
	"<td>8</td>",
	"<td>1</td>",
	"<td>39.99&nbsp;USD</td>",
	"</tr>",
	"</tbody>",
	'<tfoot style="text-align:right;text-transform:uppercase">',
	'<tr><td colspan="5">Total products:</td><td>189.86&nbsp;USD</td></tr>',
	'<tr><td colspan="5"><strong>Total:</strong></td><td><strong>189.86&nbsp;USD</strong></td></tr>',
	"</tfoot>",
	"</table></div></div></div>",
].join("\n");
